# Approved build scripts for pnpm
# These packages are allowed to run their postinstall/build scripts
@apollo/protobufjs: true
@prisma/client: true
@prisma/engines: true
@scarf/scarf: true
@tree-sitter-grammars/tree-sitter-yaml: true
bcrypt: true
canvas: true
core-js: true
core-js-pure: true
electron: true
keytar: true
msgpackr-extract: true
node-pty: true
prisma: true
protobufjs: true
sqlite3: true
tesseract.js: true
tree-sitter: true
tree-sitter-json: true
unrs-resolver: true
yarn: true
