packages:
  # Core packages with shared functionality
  - 'packages/*'
  - 'packages/@wundr/*'
  
  # Applications
  - 'apps/*'
  
  # Development tools and scripts
  - 'tools/*'
  
  # Configuration packages
  - 'config/*'