/**
 * Export System Examples
 *
 * This file demonstrates all the export functionality.
 * These are working examples that can be used in your application.
 */

import {
  // Main export functions
  exportData,
  exportToCSV,
  exportToPDF,
  exportToXLSX,
  exportChartToImage,
  bulkExport,

  // Template functions
  createTableReportTemplate,
  createDashboardReportTemplate,
  createFinancialReportTemplate,
  exportReportToPDF,
  getTemplateLibrary,
  saveTemplate,

  // Utility functions
  generateExportFilename,
  transformData,
  flattenData,
  estimateExportSize,
  formatFileSize,
  createProgressTracker,

  // Advanced features
  ExportManager,
  exportWithRetry,
  exportMultipleSheetsToXLSX,
  exportCompositeImage,

  // Types
  type ExportResult,
  type ExportFormat,
  type ReportSection,
} from '../lib/export';

// Sample data
interface User extends Record<string, unknown> {
  id: number;
  name: string;
  email: string;
  role: string;
  joinedAt: Date;
  isActive: boolean;
  metadata?: {
    department: string;
    location: string;
  };
}

const sampleUsers: User[] = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: 'Admin',
    joinedAt: new Date('2023-01-15'),
    isActive: true,
    metadata: {
      department: 'Engineering',
      location: 'San Francisco',
    },
  },
  {
    id: 2,
    name: 'Bob Smith',
    email: 'bob@example.com',
    role: 'User',
    joinedAt: new Date('2023-03-22'),
    isActive: true,
    metadata: {
      department: 'Sales',
      location: 'New York',
    },
  },
  {
    id: 3,
    name: 'Carol White',
    email: 'carol@example.com',
    role: 'Manager',
    joinedAt: new Date('2023-02-10'),
    isActive: false,
    metadata: {
      department: 'Marketing',
      location: 'London',
    },
  },
];

/**
 * Example 1: Basic CSV Export
 */
export async function example1_BasicCSVExport() {
  console.log('Example 1: Basic CSV Export');

  const result = await exportToCSV(sampleUsers as Record<string, unknown>[], {
    filename: 'users.csv',
    includeHeaders: true,
    delimiter: ',',
    bom: true, // Helps Excel recognize UTF-8
  });

  if (result.success) {
    console.log(
      `✓ Exported ${result.filename} (${formatFileSize(result.size)})`
    );
  } else {
    console.error('✗ Export failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 2: PDF Table Export
 */
export async function example2_PDFTableExport() {
  console.log('Example 2: PDF Table Export');

  const result = await exportToPDF(sampleUsers as Record<string, unknown>[], {
    filename: 'users_report.pdf',
    title: 'User Directory',
    orientation: 'landscape',
    pageSize: 'A4',
    includePageNumbers: true,
    includeTimestamp: true,
    headerText: 'Confidential - Internal Use Only',
    footerText: 'Generated by Wundr Export System',
  });

  if (result.success) {
    console.log(
      `✓ Exported ${result.filename} (${formatFileSize(result.size)})`
    );
  } else {
    console.error('✗ Export failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 3: Excel Export with Styling
 */
export async function example3_ExcelExport() {
  console.log('Example 3: Excel Export with Styling');

  const result = await exportToXLSX(sampleUsers, {
    filename: 'users.xlsx',
    sheetName: 'Active Users',
    autoWidth: true,
    freezeFirstRow: true,
    cellStyles: true,
    headerStyle: {
      bold: true,
      fontSize: 12,
      backgroundColor: '#428bca',
      fontColor: '#ffffff',
    },
  });

  if (result.success) {
    console.log(
      `✓ Exported ${result.filename} (${formatFileSize(result.size)})`
    );
  } else {
    console.error('✗ Export failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 4: Multiple Excel Sheets
 */
export async function example4_MultipleSheets() {
  console.log('Example 4: Multiple Excel Sheets');

  const activeUsers = sampleUsers.filter(u => u.isActive);
  const inactiveUsers = sampleUsers.filter(u => !u.isActive);

  const result = await exportMultipleSheetsToXLSX(
    {
      'Active Users': activeUsers as Record<string, unknown>[],
      'Inactive Users': inactiveUsers as Record<string, unknown>[],
      'All Users': sampleUsers as Record<string, unknown>[],
    },
    {
      filename: 'users_complete.xlsx',
      autoWidth: true,
      freezeFirstRow: true,
    }
  );

  if (result.success) {
    console.log(`✓ Exported ${result.filename} with 3 sheets`);
  } else {
    console.error('✗ Export failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 5: Chart Export
 */
export async function example5_ChartExport() {
  console.log('Example 5: Chart Export');

  // Assuming you have a chart element with id="user-chart"
  const result = await exportChartToImage('user-chart', {
    filename: 'user_statistics.png',
    format: 'png',
    scale: 2, // High resolution
    quality: 1.0,
    backgroundColor: '#ffffff',
  });

  if (result.success) {
    console.log(`✓ Exported chart as ${result.filename}`);
  } else {
    console.error('✗ Export failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 6: Flattened Data Export
 */
export async function example6_FlattenedDataExport() {
  console.log('Example 6: Flattened Data Export');

  // Flatten nested objects
  const flattenedData = flattenData(sampleUsers, {
    maxDepth: 3,
    separator: '.',
  });

  const result = await exportToCSV(flattenedData as Record<string, unknown>[], {
    filename: 'users_flattened.csv',
  });

  if (result.success) {
    console.log(`✓ Exported flattened data to ${result.filename}`);
  } else {
    console.error('✗ Export failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 7: Data Transformation
 */
export async function example7_DataTransformation() {
  console.log('Example 7: Data Transformation');

  const transformedData = transformData(sampleUsers, {
    flatten: true,
    dateFormat: 'yyyy-MM-dd',
    booleanFormat: 'yes/no',
    nullValue: 'N/A',
    undefinedValue: '',
  });

  const result = await exportToXLSX(
    transformedData as Record<string, unknown>[],
    {
      filename: 'users_transformed.xlsx',
    }
  );

  if (result.success) {
    console.log(`✓ Exported transformed data to ${result.filename}`);
  } else {
    console.error('✗ Export failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 8: Report Template - Basic
 */
export async function example8_BasicReportTemplate() {
  console.log('Example 8: Basic Report Template');

  const template = createTableReportTemplate('User Report', {
    title: 'Monthly User Report',
    description: 'Active and inactive users summary',
    includeTimestamp: true,
    includeSummary: true,
  });

  // Add data to template sections
  const sections = template.sections.map(section => {
    if (section.type === 'table') {
      return { ...section, content: sampleUsers };
    }
    if (section.id === 'summary') {
      return {
        ...section,
        content: `Total Users: ${sampleUsers.length}\nActive: ${sampleUsers.filter(u => u.isActive).length}\nInactive: ${sampleUsers.filter(u => !u.isActive).length}`,
      };
    }
    return section;
  });

  const result = await exportReportToPDF(sections, {
    filename: 'user_report.pdf',
    title: template.name,
  });

  if (result.success) {
    console.log(`✓ Generated report: ${result.filename}`);
  } else {
    console.error('✗ Report generation failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 9: Dashboard Report with Charts
 */
export async function example9_DashboardReport() {
  console.log('Example 9: Dashboard Report with Charts');

  const template = createDashboardReportTemplate(
    'User Analytics Dashboard',
    ['user-growth-chart', 'department-chart', 'activity-chart'],
    {
      title: 'Q4 2024 User Analytics',
      description: 'Comprehensive user analytics for Q4',
      includeDataTables: true,
    }
  );

  const sections = template.sections.map(section => {
    if (section.type === 'table') {
      return { ...section, content: sampleUsers as Record<string, unknown>[] };
    }
    return section;
  });

  const result = await exportReportToPDF(sections, {
    filename: 'dashboard_report.pdf',
    orientation: 'landscape',
  });

  if (result.success) {
    console.log(`✓ Generated dashboard: ${result.filename}`);
  } else {
    console.error('✗ Dashboard generation failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 10: Financial Report
 */
export async function example10_FinancialReport() {
  console.log('Example 10: Financial Report');

  const template = createFinancialReportTemplate('Q4 Financial Summary', {
    title: 'Quarterly Financial Report',
    period: 'Q4 2024',
    includeCharts: true,
  });

  // Mock financial data
  const financialData = [
    { category: 'Revenue', Q1: 150000, Q2: 175000, Q3: 200000, Q4: 225000 },
    { category: 'Expenses', Q1: 100000, Q2: 110000, Q3: 120000, Q4: 130000 },
    { category: 'Profit', Q1: 50000, Q2: 65000, Q3: 80000, Q4: 95000 },
  ];

  const sections = template.sections.map(section => {
    if (section.type === 'table') {
      return { ...section, content: financialData };
    }
    return section;
  });

  const result = await exportReportToPDF(sections, {
    filename: 'financial_report_q4.pdf',
  });

  if (result.success) {
    console.log(`✓ Generated financial report: ${result.filename}`);
  } else {
    console.error('✗ Report generation failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 11: Bulk Export (Multiple Formats)
 */
export async function example11_BulkExport() {
  console.log('Example 11: Bulk Export (Multiple Formats)');

  const results = await bulkExport(sampleUsers as Record<string, unknown>[], {
    formats: ['csv', 'xlsx', 'pdf'],
    baseFilename: 'users_export',
    parallel: true,
    onProgress: (format, progress) => {
      console.log(`  ${format}: ${progress.status} (${progress.progress}%)`);
    },
  });

  console.log('\nExport Results:');
  for (const [format, result] of Object.entries(results)) {
    if (result.success) {
      console.log(
        `  ✓ ${format}: ${result.filename} (${formatFileSize(result.size)})`
      );
    } else {
      console.log(`  ✗ ${format}: Failed - ${result.error?.message}`);
    }
  }

  return results;
}

/**
 * Example 12: Export Manager (Queue)
 */
export async function example12_ExportManager() {
  console.log('Example 12: Export Manager with Queue');

  const manager = new ExportManager(3); // Max 3 concurrent exports

  console.log('Adding exports to queue...');

  const promises = [
    manager.add(sampleUsers as Record<string, unknown>[], 'csv', {
      filename: 'queue_export_1.csv',
    }),
    manager.add(sampleUsers as Record<string, unknown>[], 'xlsx', {
      filename: 'queue_export_2.xlsx',
    }),
    manager.add(sampleUsers as Record<string, unknown>[], 'pdf', {
      filename: 'queue_export_3.pdf',
    }),
  ];

  console.log(`Queue size: ${manager.getQueueSize()}`);

  const results = await Promise.all(promises);

  console.log('\nQueue Processing Results:');
  results.forEach((result, index) => {
    if (result.success) {
      console.log(`  ✓ Export ${index + 1}: ${result.filename}`);
    } else {
      console.log(`  ✗ Export ${index + 1}: Failed`);
    }
  });

  return results;
}

/**
 * Example 13: Export with Retry
 */
export async function example13_ExportWithRetry() {
  console.log('Example 13: Export with Retry Logic');

  const result = await exportWithRetry(
    sampleUsers as Record<string, unknown>[],
    'pdf',
    {
      filename: 'retry_export.pdf',
      maxRetries: 3,
      retryDelay: 1000,
    }
  );

  if (result.success) {
    console.log(`✓ Export succeeded: ${result.filename}`);
  } else {
    console.log(`✗ Export failed after all retries: ${result.error?.message}`);
  }

  return result;
}

/**
 * Example 14: Progress Tracking
 */
export async function example14_ProgressTracking() {
  console.log('Example 14: Progress Tracking');

  const tracker = createProgressTracker(sampleUsers.length, progress => {
    console.log(`  Processing: ${progress}%`);
  });

  // Simulate processing
  for (let i = 0; i < sampleUsers.length; i++) {
    // Process item
    await new Promise(resolve => setTimeout(resolve, 100));
    tracker.increment();
  }

  tracker.complete();
  console.log('✓ Processing complete!');
}

/**
 * Example 15: File Size Estimation
 */
export function example15_FileSizeEstimation() {
  console.log('Example 15: File Size Estimation');

  const formats: ExportFormat[] = ['csv', 'xlsx', 'pdf', 'json'];

  console.log('\nEstimated export sizes:');
  formats.forEach(format => {
    const estimatedBytes = estimateExportSize(sampleUsers, format);
    console.log(`  ${format.toUpperCase()}: ${formatFileSize(estimatedBytes)}`);
  });
}

/**
 * Example 16: Custom Filename Generation
 */
export function example16_CustomFilenames() {
  console.log('Example 16: Custom Filename Generation');

  const formats: ExportFormat[] = ['csv', 'xlsx', 'pdf'];

  console.log('\nGenerated filenames:');
  formats.forEach(format => {
    const filename = generateExportFilename('user_export', format, {
      includeTimestamp: true,
      suffix: 'final',
    });
    console.log(`  ${format}: ${filename}`);
  });
}

/**
 * Example 17: Composite Chart Export
 */
export async function example17_CompositeChartExport() {
  console.log('Example 17: Composite Chart Export');

  // Export multiple charts into a single image
  const result = await exportCompositeImage(
    [
      { element: 'chart-1', x: 0, y: 0, width: 400, height: 300 },
      { element: 'chart-2', x: 420, y: 0, width: 400, height: 300 },
      { element: 'chart-3', x: 0, y: 320, width: 400, height: 300 },
      { element: 'chart-4', x: 420, y: 320, width: 400, height: 300 },
    ],
    { width: 840, height: 640 },
    {
      filename: 'dashboard_composite.png',
      format: 'png',
      backgroundColor: '#f5f5f5',
    }
  );

  if (result.success) {
    console.log(`✓ Composite chart exported: ${result.filename}`);
  } else {
    console.error('✗ Export failed:', result.error?.message);
  }

  return result;
}

/**
 * Example 18: Template Library
 */
export function example18_TemplateLibrary() {
  console.log('Example 18: Template Library');

  const library = getTemplateLibrary();

  console.log('\nAvailable Templates:');
  Object.entries(library).forEach(([key, template]) => {
    console.log(`  ${key}: ${template.name}`);
    console.log(`    - ${template.description || 'No description'}`);
    console.log(`    - Sections: ${template.sections.length}`);
  });
}

/**
 * Run all examples
 */
export async function runAllExamples() {
  console.log('='.repeat(60));
  console.log('EXPORT SYSTEM EXAMPLES');
  console.log('='.repeat(60));

  // Non-async examples
  console.log('\n--- File Size Estimation ---');
  example15_FileSizeEstimation();

  console.log('\n--- Custom Filenames ---');
  example16_CustomFilenames();

  console.log('\n--- Template Library ---');
  example18_TemplateLibrary();

  // Note: Async examples would need to be called individually
  // in a real application context with proper UI elements (charts, etc.)

  console.log('\n='.repeat(60));
  console.log('Examples complete! Use individual functions for async exports.');
  console.log('='.repeat(60));
}
