/**
 * @neolith/core - Agent Persistence Service
 *
 * Persistence layer for Tier 3 sub-agent definitions generated by org-genesis.
 * Provides bulk save, listing, status updates, and discipline-based queries
 * against the subagent table.
 *
 * @packageDocumentation
 */

import { prisma } from '@neolith/database';

import { GenesisError } from '../errors';

import type { AgentStatus, AgentScope } from '../types/agent-enums';
import type { Prisma, PrismaClient } from '@neolith/database';

// =============================================================================
// Local Inline Types (mirrors @wundr/org-genesis agent types)
// =============================================================================

/**
 * Tool type for an agent (mirrors AgentToolType from @wundr/org-genesis).
 */
export type AgentToolType = 'mcp' | 'builtin' | 'custom';

/**
 * Agent tool definition (mirrors AgentTool from @wundr/org-genesis).
 */
export interface AgentTool {
  name: string;
  type: AgentToolType;
  config?: Record<string, unknown>;
}

/**
 * Agent capabilities (mirrors AgentCapabilities from @wundr/org-genesis).
 */
export interface AgentCapabilities {
  canReadFiles: boolean;
  canWriteFiles: boolean;
  canExecuteCommands: boolean;
  canAccessNetwork: boolean;
  canSpawnSubAgents: boolean;
  customCapabilities?: string[];
}

/**
 * Minimal shape of a Tier 3 agent definition from @wundr/org-genesis.
 * Used for persistence; full type lives in the org-genesis package.
 */
export interface AgentDefinition {
  /** External unique ID for this agent definition */
  id: string;
  /** Human-readable name */
  name: string;
  /** URL-safe slug */
  slug: string;
  /** Always 3 for sub-agents */
  tier: 3;
  /** Availability scope ('universal' | 'discipline-specific') */
  scope: string;
  /** Brief description */
  description: string;
  /** System prompt / charter text */
  charter: string;
  /** Model variant ('opus' | 'sonnet' | 'haiku') */
  model: string;
  /** Tools this agent can use */
  tools: AgentTool[];
  /** Capability permissions */
  capabilities: AgentCapabilities;
  /** Disciplines that can use this agent */
  usedByDisciplines: string[];
  /** Optional VPs that can directly invoke this agent */
  usedByVps?: string[];
  /** Search tags */
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

// =============================================================================
// Error Classes
// =============================================================================

/**
 * Error thrown when a subagent record is not found.
 */
export class AgentPersistenceNotFoundError extends GenesisError {
  constructor(agentId: string) {
    super(`Agent not found: ${agentId}`, 'AGENT_PERSISTENCE_NOT_FOUND', 404, {
      agentId,
    });
    this.name = 'AgentPersistenceNotFoundError';
  }
}

/**
 * Error thrown when agent persistence validation fails.
 */
export class AgentPersistenceValidationError extends GenesisError {
  public readonly errors: Record<string, string[]>;

  constructor(message: string, errors: Record<string, string[]>) {
    super(message, 'AGENT_PERSISTENCE_VALIDATION_ERROR', 400, { errors });
    this.name = 'AgentPersistenceValidationError';
    this.errors = errors;
  }
}

/**
 * Error thrown when an agent persistence operation fails.
 */
export class AgentPersistenceError extends GenesisError {
  constructor(operation: string, originalError?: Error) {
    super(
      `Agent persistence operation '${operation}' failed: ${originalError?.message ?? 'Unknown error'}`,
      'AGENT_PERSISTENCE_ERROR',
      500,
      { operation, originalError: originalError?.message }
    );
    this.name = 'AgentPersistenceError';
  }
}

// =============================================================================
// Types
// =============================================================================

/**
 * Persisted sub-agent record returned from the database.
 */
export interface PersistedAgent {
  id: string;
  name: string;
  description: string | null;
  charterId: string;
  charterData: Record<string, unknown>;
  sessionManagerId: string | null;
  isGlobal: boolean;
  scope: AgentScope;
  tier: number;
  capabilities: unknown;
  mcpTools: string[];
  maxTokensPerTask: number;
  worktreeRequirement: string;
  status: AgentStatus;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Input for saving a batch of agent definitions.
 */
export interface SaveAgentDefinitionsInput {
  /** Session manager to associate these agents with (nullable for global agents) */
  sessionManagerId: string | null;
  /** Agent definitions generated by org-genesis */
  agents: AgentDefinition[];
  /** Optional charter ID to tag agents with (defaults to agent.id) */
  defaultCharterId?: string;
}

/**
 * Result of a bulk agent save operation.
 */
export interface SaveAgentDefinitionsResult {
  /** Successfully persisted agents */
  saved: PersistedAgent[];
  /** Number of agents that were created (new) */
  created: number;
  /** Number of agents that were updated (upserted) */
  updated: number;
}

// =============================================================================
// Service Interface
// =============================================================================

/**
 * Interface for agent persistence operations.
 */
export interface AgentPersistenceService {
  /**
   * Bulk saves agent definitions to the subagent table.
   * Uses upsert semantics keyed on the agent's external ID stored in charterData.
   *
   * @param sessionManagerId - ID of the session manager that owns these agents
   * @param agents - Array of AgentDefinition objects to persist
   * @returns Result summary with persisted agent records
   * @throws {AgentPersistenceValidationError} If input validation fails
   * @throws {AgentPersistenceError} If the database operation fails
   */
  saveAgentDefinitions(
    sessionManagerId: string | null,
    agents: AgentDefinition[]
  ): Promise<SaveAgentDefinitionsResult>;

  /**
   * Lists all agents associated with a session manager.
   *
   * @param sessionManagerId - ID of the session manager
   * @returns Array of persisted agent records
   */
  getAgentsBySessionManager(
    sessionManagerId: string
  ): Promise<PersistedAgent[]>;

  /**
   * Updates the operational status of a single agent.
   *
   * @param agentId - ID of the subagent record (database ID)
   * @param status - New status to set
   * @returns The updated agent record
   * @throws {AgentPersistenceNotFoundError} If the agent record does not exist
   */
  updateAgentStatus(
    agentId: string,
    status: AgentStatus
  ): Promise<PersistedAgent>;

  /**
   * Lists all agents whose charterData.usedByDisciplines array contains the given discipline ID.
   *
   * @param disciplineId - Discipline identifier to filter by
   * @returns Array of persisted agent records for that discipline
   */
  getAgentsByDiscipline(disciplineId: string): Promise<PersistedAgent[]>;
}

// =============================================================================
// Service Implementation
// =============================================================================

/**
 * Implementation of AgentPersistenceService.
 */
export class AgentPersistenceServiceImpl implements AgentPersistenceService {
  private readonly db: PrismaClient;

  /**
   * Creates a new AgentPersistenceServiceImpl instance.
   *
   * @param database - Optional Prisma client (defaults to singleton)
   */
  constructor(database?: PrismaClient) {
    this.db = database ?? prisma;
  }

  // ===========================================================================
  // Public Methods
  // ===========================================================================

  /**
   * Bulk saves agent definitions, creating or updating each record in a transaction.
   */
  async saveAgentDefinitions(
    sessionManagerId: string | null,
    agents: AgentDefinition[]
  ): Promise<SaveAgentDefinitionsResult> {
    this.validateSaveInput(agents);

    let created = 0;
    let updated = 0;
    const saved: PersistedAgent[] = [];

    try {
      await this.db.$transaction(async (tx: Prisma.TransactionClient) => {
        for (const agent of agents) {
          const scope = this.mapAgentScope(agent.scope);
          const isGlobal = agent.scope === 'universal';
          const charterData = agent as unknown as Prisma.InputJsonValue;
          const capabilities =
            agent.capabilities as unknown as Prisma.InputJsonValue;

          // Check for existing record by matching agentDefinition.id stored in charterData
          // We use charterId = agent.id as the external correlation key
          const existing = await tx.subagent.findFirst({
            where: {
              charterId: agent.id,
              sessionManagerId: sessionManagerId ?? undefined,
            },
          });

          let record;
          if (existing) {
            record = await tx.subagent.update({
              where: { id: existing.id },
              data: {
                name: agent.name,
                description: agent.description,
                charterData,
                sessionManagerId,
                isGlobal,
                scope,
                capabilities,
                mcpTools: agent.tools
                  .filter(t => t.type === 'mcp')
                  .map(t => t.name),
              },
            });
            updated++;
          } else {
            record = await tx.subagent.create({
              data: {
                name: agent.name,
                description: agent.description,
                charterId: agent.id,
                charterData,
                sessionManagerId,
                isGlobal,
                scope,
                tier: 3,
                capabilities,
                mcpTools: agent.tools
                  .filter(t => t.type === 'mcp')
                  .map(t => t.name),
                maxTokensPerTask: 50000,
                worktreeRequirement: 'none',
                status: 'INACTIVE',
              },
            });
            created++;
          }

          saved.push(this.mapToRecord(record));
        }
      });
    } catch (error) {
      if (error instanceof GenesisError) {
        throw error;
      }
      throw new AgentPersistenceError(
        'saveAgentDefinitions',
        error instanceof Error ? error : undefined
      );
    }

    return { saved, created, updated };
  }

  /**
   * Lists all agents for a given session manager.
   */
  async getAgentsBySessionManager(
    sessionManagerId: string
  ): Promise<PersistedAgent[]> {
    const records = await this.db.subagent.findMany({
      where: { sessionManagerId },
      orderBy: { createdAt: 'asc' },
    });

    return records.map(r => this.mapToRecord(r));
  }

  /**
   * Updates the status of an individual agent record.
   */
  async updateAgentStatus(
    agentId: string,
    status: AgentStatus
  ): Promise<PersistedAgent> {
    const existing = await this.db.subagent.findUnique({
      where: { id: agentId },
    });

    if (!existing) {
      throw new AgentPersistenceNotFoundError(agentId);
    }

    const updated = await this.db.subagent.update({
      where: { id: agentId },
      data: { status },
    });

    return this.mapToRecord(updated);
  }

  /**
   * Lists all agents associated with a discipline.
   * Searches charterData.usedByDisciplines JSON array for the given discipline ID.
   */
  async getAgentsByDiscipline(disciplineId: string): Promise<PersistedAgent[]> {
    // Prisma JSON path filtering: charterData.usedByDisciplines array contains disciplineId
    const records = await this.db.subagent.findMany({
      where: {
        charterData: {
          path: ['usedByDisciplines'],
          array_contains: disciplineId,
        },
      },
      orderBy: { createdAt: 'asc' },
    });

    return records.map(r => this.mapToRecord(r));
  }

  // ===========================================================================
  // Private Helpers
  // ===========================================================================

  /**
   * Maps the org-genesis AgentScope string to the Prisma AgentScope enum value.
   */
  private mapAgentScope(scope: string): AgentScope {
    switch (scope) {
      case 'universal':
        return 'UNIVERSAL';
      case 'discipline-specific':
        return 'DISCIPLINE';
      default:
        return 'DISCIPLINE';
    }
  }

  /**
   * Validates the agent list before a bulk save.
   */
  private validateSaveInput(agents: AgentDefinition[]): void {
    const errors: Record<string, string[]> = {};

    if (!Array.isArray(agents)) {
      errors.agents = ['Agents must be an array'];
    } else if (agents.length === 0) {
      errors.agents = ['At least one agent definition is required'];
    } else {
      agents.forEach((agent, idx) => {
        if (!agent.id || agent.id.trim().length === 0) {
          errors[`agents[${idx}].id`] = ['Agent ID is required'];
        }
        if (!agent.name || agent.name.trim().length === 0) {
          errors[`agents[${idx}].name`] = ['Agent name is required'];
        }
        if (agent.tier !== 3) {
          errors[`agents[${idx}].tier`] = ['Agent tier must be 3'];
        }
      });
    }

    if (Object.keys(errors).length > 0) {
      throw new AgentPersistenceValidationError(
        'Agent save validation failed',
        errors
      );
    }
  }

  /**
   * Maps a raw Prisma subagent row to the typed PersistedAgent.
   */
  private mapToRecord(row: {
    id: string;
    name: string;
    description: string | null;
    charterId: string;
    charterData: Prisma.JsonValue;
    sessionManagerId: string | null;
    isGlobal: boolean;
    scope: AgentScope;
    tier: number;
    capabilities: Prisma.JsonValue;
    mcpTools: string[];
    maxTokensPerTask: number;
    worktreeRequirement: string;
    status: AgentStatus;
    createdAt: Date;
    updatedAt: Date;
  }): PersistedAgent {
    return {
      id: row.id,
      name: row.name,
      description: row.description,
      charterId: row.charterId,
      charterData: row.charterData as Record<string, unknown>,
      sessionManagerId: row.sessionManagerId,
      isGlobal: row.isGlobal,
      scope: row.scope,
      tier: row.tier,
      capabilities: row.capabilities,
      mcpTools: row.mcpTools,
      maxTokensPerTask: row.maxTokensPerTask,
      worktreeRequirement: row.worktreeRequirement,
      status: row.status,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    };
  }
}

// =============================================================================
// Factory Functions
// =============================================================================

/**
 * Creates a new AgentPersistenceService instance.
 *
 * @param database - Optional Prisma client instance
 * @returns Agent persistence service instance
 *
 * @example
 * ```typescript
 * const agentPersistence = createAgentPersistenceService();
 *
 * // Bulk save generated agents
 * const result = await agentPersistence.saveAgentDefinitions(sessionManagerId, agents);
 * console.log(`Created: ${result.created}, Updated: ${result.updated}`);
 *
 * // Update a specific agent's status
 * await agentPersistence.updateAgentStatus(agentId, 'ACTIVE');
 *
 * // List agents by discipline
 * const engineeringAgents = await agentPersistence.getAgentsByDiscipline('engineering');
 * ```
 */
export function createAgentPersistenceService(
  database?: PrismaClient
): AgentPersistenceServiceImpl {
  return new AgentPersistenceServiceImpl(database);
}

/**
 * Default agent persistence service instance using the singleton Prisma client.
 */
export const agentPersistenceService = createAgentPersistenceService();
