blank_issues_enabled: false
contact_links:
  - name: {{ORGANIZATION}} Community Support
    url: {{SUPPORT_URL}}
    about: Please ask and answer questions here.
  - name: {{ORGANIZATION}} Documentation
    url: {{DOCS_URL}}
    about: Check our documentation for common questions and guides.