export interface ConfigTemplate {
  id: string;
  name: string;
  description: string;
  tags: string[];
  config: Record<string, any>;
  features?: string[];
}

export const templates: ConfigTemplate[] = [
  {
    id: 'react-typescript',
    name: 'React TypeScript',
    description:
      'Optimized settings for React TypeScript projects with comprehensive analysis',
    tags: ['React', 'TypeScript', 'Frontend'],
    features: ['JSX Analysis', 'Type Checking', 'Component Structure'],
    config: {
      theme: 'system',
      language: 'en',
      autoSave: true,
      notifications: true,
      compactMode: false,
      sidebarCollapsed: false,
      duplicateThreshold: 0.8,
      complexityThreshold: 15,
      minFileSize: 500,
      patternsToIgnore: [
        'node_modules/**',
        'build/**',
        'dist/**',
        '.next/**',
        'coverage/**',
        '*.test.*',
        '*.spec.*',
      ],
      excludeDirectories: [
        'node_modules',
        'build',
        'dist',
        '.next',
        'coverage',
      ],
      includeFileTypes: ['.ts', '.tsx', '.js', '.jsx', '.json'],
      enableSmartAnalysis: true,
      analysisDepth: 'medium',
      defaultFormats: ['json', 'html', 'csv'],
      includeMetadata: true,
      compressionEnabled: false,
      timestampFiles: true,
    },
  },
  {
    id: 'node-backend',
    name: 'Node.js Backend',
    description: 'Configuration tailored for Node.js backend services and APIs',
    tags: ['Node.js', 'Backend', 'API'],
    features: ['API Analysis', 'Performance Metrics', 'Security Patterns'],
    config: {
      theme: 'dark',
      language: 'en',
      autoSave: true,
      notifications: true,
      compactMode: true,
      sidebarCollapsed: false,
      duplicateThreshold: 0.75,
      complexityThreshold: 20,
      minFileSize: 1000,
      patternsToIgnore: [
        'node_modules/**',
        'dist/**',
        'build/**',
        'logs/**',
        '*.test.*',
        '*.spec.*',
        'coverage/**',
      ],
      excludeDirectories: ['node_modules', 'dist', 'build', 'logs'],
      includeFileTypes: ['.js', '.ts', '.json', '.sql'],
      enableSmartAnalysis: true,
      analysisDepth: 'deep',
      defaultFormats: ['json', 'csv'],
      includeMetadata: true,
      compressionEnabled: true,
      timestampFiles: true,
    },
  },
  {
    id: 'python-ml',
    name: 'Python Machine Learning',
    description:
      'Settings optimized for Python ML projects with notebook support',
    tags: ['Python', 'ML', 'Data Science'],
    features: ['Notebook Analysis', 'Model Validation', 'Data Pipeline Review'],
    config: {
      theme: 'light',
      language: 'en',
      autoSave: false,
      notifications: true,
      compactMode: false,
      sidebarCollapsed: false,
      duplicateThreshold: 0.7,
      complexityThreshold: 25,
      minFileSize: 2000,
      patternsToIgnore: [
        '__pycache__/**',
        '.pytest_cache/**',
        'venv/**',
        'env/**',
        '*.pyc',
        'data/**',
        'models/**',
        'checkpoints/**',
      ],
      excludeDirectories: ['__pycache__', 'venv', 'env', 'data', 'models'],
      includeFileTypes: ['.py', '.ipynb', '.yml', '.yaml', '.json'],
      enableSmartAnalysis: true,
      analysisDepth: 'deep',
      defaultFormats: ['html', 'pdf', 'json'],
      includeMetadata: true,
      compressionEnabled: true,
      timestampFiles: true,
    },
  },
  {
    id: 'vue-spa',
    name: 'Vue.js SPA',
    description: 'Configuration for Vue.js single page applications',
    tags: ['Vue.js', 'SPA', 'Frontend'],
    features: [
      'Component Analysis',
      'Vuex State Management',
      'Router Patterns',
    ],
    config: {
      theme: 'system',
      language: 'en',
      autoSave: true,
      notifications: true,
      compactMode: false,
      sidebarCollapsed: false,
      duplicateThreshold: 0.8,
      complexityThreshold: 12,
      minFileSize: 500,
      patternsToIgnore: [
        'node_modules/**',
        'dist/**',
        '.nuxt/**',
        'coverage/**',
        '*.test.*',
        '*.spec.*',
      ],
      excludeDirectories: ['node_modules', 'dist', '.nuxt'],
      includeFileTypes: ['.vue', '.js', '.ts', '.json', '.scss', '.css'],
      enableSmartAnalysis: false,
      analysisDepth: 'medium',
      defaultFormats: ['html', 'json'],
      includeMetadata: true,
      compressionEnabled: false,
      timestampFiles: true,
    },
  },
  {
    id: 'golang-microservices',
    name: 'Go Microservices',
    description: 'Optimized for Go microservices architecture',
    tags: ['Go', 'Microservices', 'Backend'],
    features: [
      'Service Analysis',
      'Performance Profiling',
      'Dependency Tracking',
    ],
    config: {
      theme: 'dark',
      language: 'en',
      autoSave: true,
      notifications: false,
      compactMode: true,
      sidebarCollapsed: true,
      duplicateThreshold: 0.85,
      complexityThreshold: 15,
      minFileSize: 1500,
      patternsToIgnore: [
        'vendor/**',
        'bin/**',
        '*_test.go',
        'testdata/**',
        '.git/**',
      ],
      excludeDirectories: ['vendor', 'bin', 'testdata'],
      includeFileTypes: ['.go', '.mod', '.sum', '.yaml', '.yml'],
      enableSmartAnalysis: true,
      analysisDepth: 'deep',
      defaultFormats: ['json', 'csv'],
      includeMetadata: false,
      compressionEnabled: true,
      timestampFiles: true,
    },
  },
  {
    id: 'java-enterprise',
    name: 'Java Enterprise',
    description: 'Configuration for large-scale Java enterprise applications',
    tags: ['Java', 'Enterprise', 'Spring'],
    features: ['Spring Boot Analysis', 'JPA Patterns', 'Security Review'],
    config: {
      theme: 'light',
      language: 'en',
      autoSave: false,
      notifications: true,
      compactMode: false,
      sidebarCollapsed: false,
      duplicateThreshold: 0.75,
      complexityThreshold: 30,
      minFileSize: 2500,
      patternsToIgnore: [
        'target/**',
        '.mvn/**',
        '*.class',
        'logs/**',
        '*Test.java',
        '*Tests.java',
      ],
      excludeDirectories: ['target', '.mvn', 'logs'],
      includeFileTypes: ['.java', '.xml', '.properties', '.yml', '.yaml'],
      enableSmartAnalysis: true,
      analysisDepth: 'deep',
      defaultFormats: ['html', 'xml', 'json'],
      includeMetadata: true,
      compressionEnabled: true,
      timestampFiles: true,
    },
  },
  {
    id: 'mobile-react-native',
    name: 'React Native Mobile',
    description: 'Settings for React Native mobile application development',
    tags: ['React Native', 'Mobile', 'JavaScript'],
    features: ['Mobile Patterns', 'Navigation Analysis', 'Platform Specific'],
    config: {
      theme: 'system',
      language: 'en',
      autoSave: true,
      notifications: true,
      compactMode: false,
      sidebarCollapsed: false,
      duplicateThreshold: 0.8,
      complexityThreshold: 18,
      minFileSize: 800,
      patternsToIgnore: [
        'node_modules/**',
        'android/**',
        'ios/**',
        '.expo/**',
        'coverage/**',
        '*.test.*',
      ],
      excludeDirectories: ['node_modules', 'android', 'ios', '.expo'],
      includeFileTypes: ['.js', '.jsx', '.ts', '.tsx', '.json'],
      enableSmartAnalysis: false,
      analysisDepth: 'medium',
      defaultFormats: ['json', 'html'],
      includeMetadata: true,
      compressionEnabled: false,
      timestampFiles: true,
    },
  },
  {
    id: 'minimal-starter',
    name: 'Minimal Configuration',
    description: 'Lightweight setup with minimal analysis overhead',
    tags: ['Minimal', 'Fast', 'Starter'],
    features: ['Basic Analysis', 'Quick Setup', 'Low Resource Usage'],
    config: {
      theme: 'system',
      language: 'en',
      autoSave: false,
      notifications: false,
      compactMode: true,
      sidebarCollapsed: true,
      duplicateThreshold: 0.9,
      complexityThreshold: 50,
      minFileSize: 5000,
      patternsToIgnore: [
        'node_modules/**',
        'dist/**',
        'build/**',
        '*.min.*',
        '*.bundle.*',
      ],
      excludeDirectories: ['node_modules', 'dist', 'build'],
      includeFileTypes: ['.js', '.ts', '.json'],
      enableSmartAnalysis: false,
      analysisDepth: 'shallow',
      defaultFormats: ['json'],
      includeMetadata: false,
      compressionEnabled: false,
      timestampFiles: false,
    },
  },
];

export const getTemplateById = (id: string): ConfigTemplate | undefined => {
  return templates.find(template => template.id === id);
};

export const getTemplatesByTag = (tag: string): ConfigTemplate[] => {
  return templates.filter(template => template.tags.includes(tag));
};

export const getAllTags = (): string[] => {
  const tags = new Set<string>();
  templates.forEach(template => {
    template.tags.forEach(tag => tags.add(tag));
  });
  return Array.from(tags).sort();
};
