#!/bin/bash
# Post-push hook for deployment monitoring
# Auto-generated by Wundr Computer Setup

BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Only trigger for main/master
if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
  echo "🚀 Push to $BRANCH detected, initiating deployment monitoring..."

  # Detect platform
  PLATFORM=""
  if [ -f "railway.json" ] || [ -n "$RAILWAY_PROJECT_ID" ]; then
    PLATFORM="railway"
    echo "🚂 Railway platform detected"
  elif [ -f "netlify.toml" ] || [ -n "$NETLIFY_SITE_ID" ]; then
    PLATFORM="netlify"
    echo "🌐 Netlify platform detected"
  fi

  if [ -n "$PLATFORM" ]; then
    # Notify Claude Flow to start monitoring
    npx claude-flow@alpha hooks post-push \
      --platform "$PLATFORM" \
      --branch "$BRANCH" \
      --auto-monitor true

    echo "📡 Deployment monitoring initiated for $PLATFORM"
    echo "   Use '/deploy-monitor' in Claude Code for detailed status"
  else
    echo "ℹ️  No deployment platform detected"
    echo "   To enable monitoring, configure railway.json or netlify.toml"
  fi
else
  echo "ℹ️  Push to $BRANCH - skipping deployment monitoring (only main/master)"
fi
