import { BaseInstaller } from './index';
import { SetupPlatform, SetupStep, DeveloperProfile } from '../types';
export declare class LinuxInstaller implements BaseInstaller {
    name: string;
    private distro;
    isSupported(platform: SetupPlatform): boolean;
    isInstalled(): Promise<boolean>;
    getVersion(): Promise<string | null>;
    install(profile: DeveloperProfile, platform: SetupPlatform): Promise<void>;
    configure(profile: DeveloperProfile, platform: SetupPlatform): Promise<void>;
    validate(): Promise<boolean>;
    getSteps(profile: DeveloperProfile, platform: SetupPlatform): SetupStep[];
    private detectDistro;
    private updatePackageManager;
    private installEssentialPackages;
    private getEssentialPackages;
    private installDevelopmentTools;
    private installFrontendTools;
    private installBackendTools;
    private installDevOpsTools;
    private installDevOpsTool;
    private installTerraform;
    private installKubectl;
    private installMobileTools;
    private installMLTools;
    private installCommonDevTools;
    private installVSCode;
    private installGitHubCLI;
    private installSnapPackages;
    private installFlatpakPackages;
    private installFlatpak;
    private getSnapPackages;
    private getFlatpakPackages;
    private configureSystem;
    private configureShell;
    private configureZsh;
    private configureFish;
    private configureBash;
    private setupDotfiles;
    private configureFirewall;
    private isSnapSupported;
    private isFlatpakSupported;
    private validateEssentialPackages;
    private validateDevelopmentTools;
    private validateSystemConfig;
    private validateShellConfig;
    private validateSnapPackages;
}
//# sourceMappingURL=linux-installer.d.ts.map