version: '3'

services:
  {{PROJECT_NAME}}:
    build: .
    ports:
      - "{{HOST_PORT}}:{{CONTAINER_PORT}}"
    environment:
      - NODE_ENV={{NODE_ENV}}
      {{#DATABASE_URL}}- DATABASE_URL={{DATABASE_URL}}{{/DATABASE_URL}}
      {{#REDIS_URL}}- REDIS_URL={{REDIS_URL}}{{/REDIS_URL}}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - {{PROJECT_NAME}}-network
    {{#DEPENDS_ON}}depends_on:
      {{#POSTGRES}}- postgres{{/POSTGRES}}
      {{#REDIS}}- redis{{/REDIS}}{{/DEPENDS_ON}}

  {{#INCLUDE_POSTGRES}}postgres:
    image: postgres:{{POSTGRES_VERSION}}-alpine
    environment:
      POSTGRES_USER: {{POSTGRES_USER}}
      POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
      POSTGRES_DB: {{POSTGRES_DB}}
    ports:
      - "{{POSTGRES_HOST_PORT}}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - {{PROJECT_NAME}}-network{{/INCLUDE_POSTGRES}}

  {{#INCLUDE_REDIS}}redis:
    image: redis:{{REDIS_VERSION}}-alpine
    ports:
      - "{{REDIS_HOST_PORT}}:6379"
    networks:
      - {{PROJECT_NAME}}-network{{/INCLUDE_REDIS}}

volumes:
  {{#INCLUDE_POSTGRES}}postgres-data:{{/INCLUDE_POSTGRES}}

networks:
  {{PROJECT_NAME}}-network:
    driver: bridge