# pnpm-workspace.yaml
# ===================
#
# Neolith workspace configuration for Netlify deployment.
# This file makes neolith a standalone workspace for deployment purposes.
#
# IMPORTANT: This workspace is designed for deployment builds where
# neolith is the base directory. The node-linker=hoisted setting in
# .npmrc ensures flat node_modules for Netlify Lambda compatibility.

packages:
  # Application packages
  - "apps/*"

  # Shared library packages (scoped under @neolith)
  - "packages/@neolith/*"
