/**
 * @neolith/org-integration - Type Definitions
 *
 * Mirrors and extends types from @wundr/org-genesis for integration purposes.
 */

// ============================================================================
// Neolith Configuration Types (mirrors org-genesis input)
// ============================================================================

/**
 * Input configuration for Neolith organization generation.
 * This mirrors the input structure expected by @wundr/org-genesis.
 */
export interface NeolithConfig {
  /** Organization name */
  organizationName: string;

  /** Organization type/industry */
  organizationType: string;

  /** Brief description of the organization's purpose */
  description: string;

  /** Investment strategy or business focus */
  strategy: string;

  /** Target assets or markets */
  targetAssets: string[];

  /** Risk tolerance level */
  riskTolerance: 'conservative' | 'moderate' | 'aggressive';

  /** Team size preference */
  teamSize: 'small' | 'medium' | 'large';

  /** Optional seed for deterministic generation */
  seed?: string;

  /** Additional configuration options */
  options?: NeolithConfigOptions;
}

/**
 * Additional options for Neolith configuration.
 */
export interface NeolithConfigOptions {
  /** Enable verbose logging during generation */
  verbose?: boolean;

  /** Custom output directory */
  outputDir?: string;

  /** Include optional disciplines */
  includeOptionalDisciplines?: boolean;

  /** Custom discipline overrides */
  disciplineOverrides?: Record<string, Partial<DisciplineDefinition>>;
}

// ============================================================================
// Neolith Result Types
// ============================================================================

/**
 * Complete result from org-genesis generation.
 */
export interface NeolithResult {
  /** Generated organization manifest */
  manifest: OrganizationManifest;

  /** List of generated Orchestrator definitions */
  orchestrators: OrchestratorDefinition[];

  /** List of generated discipline definitions */
  disciplines: DisciplineDefinition[];

  /** List of generated agent definitions */
  agents: AgentDefinition[];

  /** Generation metadata */
  metadata: NeolithMetadata;
}

/**
 * Organization manifest generated by org-genesis.
 */
export interface OrganizationManifest {
  /** Organization unique identifier */
  id: string;

  /** Organization name */
  name: string;

  /** Organization description */
  description: string;

  /** Organization type */
  type: string;

  /** Mission statement */
  mission: string;

  /** Vision statement */
  vision: string;

  /** Core values */
  values: string[];

  /** Creation timestamp */
  createdAt: string;

  /** Version of the manifest schema */
  schemaVersion: string;
}

/**
 * Orchestrator definition from org-genesis.
 */
export interface OrchestratorDefinition {
  /** Orchestrator unique identifier */
  id: string;

  /** Orchestrator role name */
  name: string;

  /** Orchestrator title */
  title: string;

  /** Orchestrator responsibilities */
  responsibilities: string[];

  /** Disciplines this Orchestrator oversees */
  disciplines: string[];

  /** Orchestrator persona/character definition */
  persona: OrchestratorPersona;

  /** KPIs for this Orchestrator */
  kpis: string[];
}

/**
 * Orchestrator persona definition.
 */
export interface OrchestratorPersona {
  /** Communication style */
  communicationStyle: string;

  /** Decision-making approach */
  decisionMakingStyle: string;

  /** Background/expertise */
  background: string;

  /** Personality traits */
  traits: string[];
}

/**
 * Discipline definition from org-genesis.
 */
export interface DisciplineDefinition {
  /** Discipline unique identifier */
  id: string;

  /** Discipline name */
  name: string;

  /** Discipline description */
  description: string;

  /** Parent OrchestratorID */
  orchestratorId: string;

  /** Slug for channel naming */
  slug: string;

  /** Purpose of this discipline */
  purpose: string;

  /** Key activities */
  activities: string[];

  /** Required capabilities */
  capabilities: string[];
}

/**
 * Agent definition from org-genesis.
 */
export interface AgentDefinition {
  /** Agent unique identifier */
  id: string;

  /** Agent name */
  name: string;

  /** Agent role */
  role: string;

  /** Parent discipline ID */
  disciplineId: string;

  /** Agent capabilities */
  capabilities: string[];

  /** Agent instructions/prompt */
  instructions: string;
}

/**
 * Metadata about the generation process.
 */
export interface NeolithMetadata {
  /** Generation timestamp */
  generatedAt: string;

  /** org-genesis version used */
  generatorVersion: string;

  /** Input configuration hash */
  configHash: string;

  /** Generation duration in ms */
  durationMs: number;
}

// ============================================================================
// OrchestratorMapping Types
// ============================================================================

/**
 * Mapping between Orchestrator definition and Slack user.
 */
export interface OrchestratorMapping {
  /** Original Orchestrator definition */
  orchestrator: OrchestratorDefinition;

  /** Generated Slack user ID */
  slackUserId: string;

  /** Slack display name */
  slackDisplayName: string;

  /** Slack user email (for app-based users) */
  slackEmail?: string;

  /** Avatar URL */
  avatarUrl?: string;

  /** Mapping status */
  status: MappingStatus;

  /** Error message if mapping failed */
  error?: string;
}

/**
 * Collection of Orchestrator mappings with summary.
 */
export interface OrchestratorMappingResult {
  /** Individual Orchestrator mappings */
  mappings: OrchestratorMapping[];

  /** Total Orchestrators processed */
  total: number;

  /** Successfully mapped count */
  successful: number;

  /** Failed mapping count */
  failed: number;

  /** Mapping timestamp */
  mappedAt: string;
}

// ============================================================================
// Discipline Mapping Types
// ============================================================================

/**
 * Mapping between discipline and Slack channel.
 */
export interface DisciplineMapping {
  /** Original discipline definition */
  discipline: DisciplineDefinition;

  /** Generated Slack channel ID */
  slackChannelId: string;

  /** Slack channel name */
  slackChannelName: string;

  /** Channel topic */
  topic?: string;

  /** Channel purpose/description */
  purpose?: string;

  /** Whether channel is private */
  isPrivate: boolean;

  /** Mapping status */
  status: MappingStatus;

  /** Error message if mapping failed */
  error?: string;
}

/**
 * Collection of discipline mappings with summary.
 */
export interface DisciplineMappingResult {
  /** Individual discipline mappings */
  mappings: DisciplineMapping[];

  /** Total disciplines processed */
  total: number;

  /** Successfully mapped count */
  successful: number;

  /** Failed mapping count */
  failed: number;

  /** Mapping timestamp */
  mappedAt: string;
}

// ============================================================================
// Common Types
// ============================================================================

/**
 * Status of a mapping operation.
 */
export type MappingStatus = 'pending' | 'success' | 'failed' | 'skipped';

/**
 * Combined migration result.
 */
export interface MigrationResult {
  /** Orchestrator mapping results */
  orchestratorMappings: OrchestratorMappingResult;

  /** Discipline mapping results */
  disciplineMappings: DisciplineMappingResult;

  /** Overall migration status */
  status: 'complete' | 'partial' | 'failed';

  /** Migration timestamp */
  migratedAt: string;

  /** Any warnings during migration */
  warnings: string[];
}

/**
 * Options for migration process.
 */
export interface MigrationOptions {
  /** Slack workspace ID */
  workspaceId: string;

  /** Dry run mode - don't create actual resources */
  dryRun?: boolean;

  /** Skip Orchestrator creation */
  skipOrchestrators?: boolean;

  /** Skip channel creation */
  skipChannels?: boolean;

  /** Channel name prefix */
  channelPrefix?: string;

  /** Make channels private */
  privateChannels?: boolean;

  /** Verbose logging */
  verbose?: boolean;
}
